services:
  orbbecsdk_ros2_jazzy:
    build:
      context: ..
      dockerfile: docker/orbbecsdk_ros2.Dockerfile
    image: orbbecsdk_ros2_jazzy
    container_name: orbbecsdk_ros2_jazzy_container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /dev:/dev:rw
      - /etc/udev/rules.d:/etc/udev/rules.d
      - /run/udev:/run/udev
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
    env_file: .env
    command: ["ros2", "launch", "orbbec_camera", "femto_bolt.launch.py", "diagnostic_period:=0.0"]
    entrypoint: ["/home/haru/entrypoint.sh"]
